from .logits_distiller import Logits_Distiller
from .logits_distiller_dwa import Logits_Distiller_DWA
from .features_distiller import Features_Distiller
from .features_distiller_dwa import Features_Distiller_DWA
from .relations_distiller import Relations_Distiller

del logits_distiller
del logits_distiller_dwa
del features_distiller
del features_distiller_dwa
del relations_distiller